---
title: "git_00"
author: "Jonathan Campos"
date: "summer 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

Twinkle, twinkle, little bat!


How I wonder what you're at!


Up above the world you fly,


Like a tea tray in the sky


There is no fifth line. 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Some say the world will end in fire,


Some say in ice.


From what I’ve tasted of desire


I hold with those who favor fire.


But if it had to perish twice,


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,


      Shining with all his might:
      
      
He did his very best to make


      The billows smooth and bright —
      
      
And this was odd, because it was


      The middle of the night.

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

T is not too late to seek a newer world.


Push off, and sitting well in order smite


The sounding furrows; for my purpose holds


To sail beyond the sunset, and the baths


Of all the western stars, until I die.


It may be that the gulfs will wash us down:


It may be we shall touch the Happy Isles,


And see the great Achilles, whom we knew.


Tho' much is taken, much abides; and tho'


We are not now that strength which in old days


Moved earth and heaven, that which we are, we are;


One equal temper of heroic hearts,


Made weak by time and fate, but strong in will


To strive, to seek, to find, and not to yield.”

